spring:
  datasource:
    url: ${REAL_DATABASE_URL}
    username: ${REAL_DATABASE_USER}
    password: ${REAL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace